// <auto-generated />
using CoronaVirusContinentApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoronaVirusContinentApi.Migrations
{
    [DbContext(typeof(CoronaVirusContinentApiContext))]
    [Migration("20200729181035_Inital-Migration")]
    partial class InitalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoronaVirusContinentApi.Models.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Continent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "آسیا"
                        },
                        new
                        {
                            Id = 2,
                            Name = "آمریکا"
                        },
                        new
                        {
                            Id = 3,
                            Name = "آفریقا"
                        },
                        new
                        {
                            Id = 4,
                            Name = "استرالیا"
                        },
                        new
                        {
                            Id = 5,
                            Name = "اروپا"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
